spring:
   datasource:
      url: jdbc:mysql://localhost:3306/testdb
      username: root
      password: root
   jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
   security:
      user:
         username: user
         password: user123